spring.application.name=backend

spring.mongodb.uri=mongodb+srv://kaviyabharathiias09_db_user:kaviyabharathi_2009@kaviyabharathi.vuxibyd.mongodb.net/?appName=kaviyabharathi

spring.mongodb.database=student_feedback